podversion = String.new(`pod --version`)
if (Gem::Version.new(podversion) >= Gem::Version.new('0.35.0'))
	source 'https://github.com/CocoaPods/Specs.git'
end

target 'VersionIntrospection', :exclusive => true do
  pod "VersionIntrospection", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "VersionIntrospection", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

post_install do | installer |
  require 'fileutils'
  puts Dir.pwd
  acknowledgementFilePlist = 'Pods/Target Support Files/Pods-VersionIntrospection/Pods-VersionIntrospection-Acknowledgements.plist'
  acknowledgementFilePlistFallback = 'Pods/Target Support Files/Pods-VersionIntrospection/Pods-VersionIntrospection-acknowledgements.plist'
	if (File.exist?(acknowledgementFilePlist))
		FileUtils.cp_r(acknowledgementFilePlist, 'Acknowledgements.plist', :remove_destination => true)
	else
		if (File.exist?(acknowledgementFilePlistFallback))
			FileUtils.cp_r(acknowledgementFilePlistFallback, 'Acknowledgements.plist', :remove_destination => true)
		end
	end
	
	acknowledgementFileMarkdown = 'Pods/Target Support Files/Pods-VersionIntrospection/Pods-VersionIntrospection-Acknowledgements.markdown'
	acknowledgementFileMarkdownFallback = 'Pods/Target Support Files/Pods-VersionIntrospection/Pods-VersionIntrospection-acknowledgements.markdown'
	if (File.exist?(acknowledgementFileMarkdown))
		FileUtils.cp_r(acknowledgementFileMarkdown, 'Acknowledgements.markdown', :remove_destination => true)
	else
		if (File.exist?(acknowledgementFileMarkdownFallback))
			FileUtils.cp_r(acknowledgementFileMarkdownFallback, 'Acknowledgements.markdown', :remove_destination => true)
		end
	end
end